### PR TITLE
Protected routing

### PR DESCRIPTION
**Pull request by bradenwatkins**

### CODE REVIEW

**Comment by bradenwatkins** [comment]
Wait, but if I refresh, it always kicks me back out to the login screen...

**Comment by tylermercer** [comment]
Might be good to clean up the git history. I noticed there are seven commits that are duplicated for some reason.

**Comment by bradenwatkins** [comment]
@tylermercer I revised the git history by squashing it into a single commit 🤷🏻‍♂️

**Comment by bradenwatkins** [comment]
@kadenBeckstead Would you review my changes? Then we can get this merged.

**Pull request merged**
